server:
  port: 8101
  servlet:
    context-path: /consumer
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    #password: 123456
    #resources:
    #static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/drgnmon?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    allow-bean-definition-overriding: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000

service-url:
  nacos-user-service: http://
feign:
  client:
    config:
      default: #default全局有效，service id指定应用有效
        connectTimeout: 3000  # 相当于Request.Optionsn 连接超时时间
        readTimeout: 10000     # 相当于Request.Options 读取超时时间
        loggerLevel: full     # 配置Feign的日志级别，相当于代码配置方式中的Logger
  hystrix:
    enabled: true
  circuitbreaker:
    enabled: true
    #sentinel:
    #enabled: true

logging: #feign 日志打印
  level:
    com.drgn.consumer.feign.drgnmon.service.inter.MyPmService: debug

#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

#雪花id
SnowFlake:
  datacenterId: 1 #服务id
  machineId: 1 #集群id
