server:
  port: 8201
  servlet:
    context-path: /hystrix

spring:
  application:
    name: hystrix
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"

#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"